// Copyright 2025 Chaukas AI
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: chaukas/spec/server/v1/server.proto

package v1

import (
	v1 "github.com/chaukasai/chaukas-spec/chaukas/spec/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Server-specific response types
type IngestEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ProcessedAt   int64                  `protobuf:"varint,3,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestEventResponse) Reset() {
	*x = IngestEventResponse{}
	mi := &file_chaukas_spec_server_v1_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEventResponse) ProtoMessage() {}

func (x *IngestEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chaukas_spec_server_v1_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEventResponse.ProtoReflect.Descriptor instead.
func (*IngestEventResponse) Descriptor() ([]byte, []int) {
	return file_chaukas_spec_server_v1_server_proto_rawDescGZIP(), []int{0}
}

func (x *IngestEventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *IngestEventResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *IngestEventResponse) GetProcessedAt() int64 {
	if x != nil {
		return x.ProcessedAt
	}
	return 0
}

type IngestEventBatchResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BatchId          string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	AcceptedCount    int32                  `protobuf:"varint,2,opt,name=accepted_count,json=acceptedCount,proto3" json:"accepted_count,omitempty"`
	RejectedCount    int32                  `protobuf:"varint,3,opt,name=rejected_count,json=rejectedCount,proto3" json:"rejected_count,omitempty"`
	RejectedEventIds []string               `protobuf:"bytes,4,rep,name=rejected_event_ids,json=rejectedEventIds,proto3" json:"rejected_event_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IngestEventBatchResponse) Reset() {
	*x = IngestEventBatchResponse{}
	mi := &file_chaukas_spec_server_v1_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEventBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEventBatchResponse) ProtoMessage() {}

func (x *IngestEventBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chaukas_spec_server_v1_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEventBatchResponse.ProtoReflect.Descriptor instead.
func (*IngestEventBatchResponse) Descriptor() ([]byte, []int) {
	return file_chaukas_spec_server_v1_server_proto_rawDescGZIP(), []int{1}
}

func (x *IngestEventBatchResponse) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *IngestEventBatchResponse) GetAcceptedCount() int32 {
	if x != nil {
		return x.AcceptedCount
	}
	return 0
}

func (x *IngestEventBatchResponse) GetRejectedCount() int32 {
	if x != nil {
		return x.RejectedCount
	}
	return 0
}

func (x *IngestEventBatchResponse) GetRejectedEventIds() []string {
	if x != nil {
		return x.RejectedEventIds
	}
	return nil
}

type GetEventStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	TimeRange     *v1.TimeRange          `protobuf:"bytes,3,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventStatsRequest) Reset() {
	*x = GetEventStatsRequest{}
	mi := &file_chaukas_spec_server_v1_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventStatsRequest) ProtoMessage() {}

func (x *GetEventStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chaukas_spec_server_v1_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventStatsRequest.ProtoReflect.Descriptor instead.
func (*GetEventStatsRequest) Descriptor() ([]byte, []int) {
	return file_chaukas_spec_server_v1_server_proto_rawDescGZIP(), []int{2}
}

func (x *GetEventStatsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetEventStatsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetEventStatsRequest) GetTimeRange() *v1.TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

type GetEventStatsResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TotalEvents          int64                  `protobuf:"varint,1,opt,name=total_events,json=totalEvents,proto3" json:"total_events,omitempty"`
	TotalSessions        int64                  `protobuf:"varint,2,opt,name=total_sessions,json=totalSessions,proto3" json:"total_sessions,omitempty"`
	EventsByType         map[string]int64       `protobuf:"bytes,3,rep,name=events_by_type,json=eventsByType,proto3" json:"events_by_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	AvgSessionDurationMs float64                `protobuf:"fixed64,4,opt,name=avg_session_duration_ms,json=avgSessionDurationMs,proto3" json:"avg_session_duration_ms,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetEventStatsResponse) Reset() {
	*x = GetEventStatsResponse{}
	mi := &file_chaukas_spec_server_v1_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventStatsResponse) ProtoMessage() {}

func (x *GetEventStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chaukas_spec_server_v1_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventStatsResponse.ProtoReflect.Descriptor instead.
func (*GetEventStatsResponse) Descriptor() ([]byte, []int) {
	return file_chaukas_spec_server_v1_server_proto_rawDescGZIP(), []int{3}
}

func (x *GetEventStatsResponse) GetTotalEvents() int64 {
	if x != nil {
		return x.TotalEvents
	}
	return 0
}

func (x *GetEventStatsResponse) GetTotalSessions() int64 {
	if x != nil {
		return x.TotalSessions
	}
	return 0
}

func (x *GetEventStatsResponse) GetEventsByType() map[string]int64 {
	if x != nil {
		return x.EventsByType
	}
	return nil
}

func (x *GetEventStatsResponse) GetAvgSessionDurationMs() float64 {
	if x != nil {
		return x.AvgSessionDurationMs
	}
	return 0
}

// Health check request
type HealthzRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthzRequest) Reset() {
	*x = HealthzRequest{}
	mi := &file_chaukas_spec_server_v1_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthzRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzRequest) ProtoMessage() {}

func (x *HealthzRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chaukas_spec_server_v1_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzRequest.ProtoReflect.Descriptor instead.
func (*HealthzRequest) Descriptor() ([]byte, []int) {
	return file_chaukas_spec_server_v1_server_proto_rawDescGZIP(), []int{4}
}

// Health check response
type HealthzResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthzResponse) Reset() {
	*x = HealthzResponse{}
	mi := &file_chaukas_spec_server_v1_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthzResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzResponse) ProtoMessage() {}

func (x *HealthzResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chaukas_spec_server_v1_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzResponse.ProtoReflect.Descriptor instead.
func (*HealthzResponse) Descriptor() ([]byte, []int) {
	return file_chaukas_spec_server_v1_server_proto_rawDescGZIP(), []int{5}
}

// Get capabilities request
type GetCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapabilitiesRequest) Reset() {
	*x = GetCapabilitiesRequest{}
	mi := &file_chaukas_spec_server_v1_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesRequest) ProtoMessage() {}

func (x *GetCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chaukas_spec_server_v1_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_chaukas_spec_server_v1_server_proto_rawDescGZIP(), []int{6}
}

// Get capabilities response
type GetCapabilitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capabilities  *v1.Capabilities       `protobuf:"bytes,1,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapabilitiesResponse) Reset() {
	*x = GetCapabilitiesResponse{}
	mi := &file_chaukas_spec_server_v1_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesResponse) ProtoMessage() {}

func (x *GetCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chaukas_spec_server_v1_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_chaukas_spec_server_v1_server_proto_rawDescGZIP(), []int{7}
}

func (x *GetCapabilitiesResponse) GetCapabilities() *v1.Capabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// Ingest single event request
type IngestEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *v1.Event              `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestEventRequest) Reset() {
	*x = IngestEventRequest{}
	mi := &file_chaukas_spec_server_v1_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEventRequest) ProtoMessage() {}

func (x *IngestEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chaukas_spec_server_v1_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEventRequest.ProtoReflect.Descriptor instead.
func (*IngestEventRequest) Descriptor() ([]byte, []int) {
	return file_chaukas_spec_server_v1_server_proto_rawDescGZIP(), []int{8}
}

func (x *IngestEventRequest) GetEvent() *v1.Event {
	if x != nil {
		return x.Event
	}
	return nil
}

// Ingest event batch request
type IngestEventBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventBatch    *v1.EventBatch         `protobuf:"bytes,1,opt,name=event_batch,json=eventBatch,proto3" json:"event_batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestEventBatchRequest) Reset() {
	*x = IngestEventBatchRequest{}
	mi := &file_chaukas_spec_server_v1_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEventBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEventBatchRequest) ProtoMessage() {}

func (x *IngestEventBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chaukas_spec_server_v1_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEventBatchRequest.ProtoReflect.Descriptor instead.
func (*IngestEventBatchRequest) Descriptor() ([]byte, []int) {
	return file_chaukas_spec_server_v1_server_proto_rawDescGZIP(), []int{9}
}

func (x *IngestEventBatchRequest) GetEventBatch() *v1.EventBatch {
	if x != nil {
		return x.EventBatch
	}
	return nil
}

// Query events request
type QueryEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *v1.QueryRequest       `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEventsRequest) Reset() {
	*x = QueryEventsRequest{}
	mi := &file_chaukas_spec_server_v1_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEventsRequest) ProtoMessage() {}

func (x *QueryEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chaukas_spec_server_v1_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEventsRequest.ProtoReflect.Descriptor instead.
func (*QueryEventsRequest) Descriptor() ([]byte, []int) {
	return file_chaukas_spec_server_v1_server_proto_rawDescGZIP(), []int{10}
}

func (x *QueryEventsRequest) GetQuery() *v1.QueryRequest {
	if x != nil {
		return x.Query
	}
	return nil
}

// Query events response
type QueryEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *v1.QueryResponse      `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEventsResponse) Reset() {
	*x = QueryEventsResponse{}
	mi := &file_chaukas_spec_server_v1_server_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEventsResponse) ProtoMessage() {}

func (x *QueryEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chaukas_spec_server_v1_server_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEventsResponse.ProtoReflect.Descriptor instead.
func (*QueryEventsResponse) Descriptor() ([]byte, []int) {
	return file_chaukas_spec_server_v1_server_proto_rawDescGZIP(), []int{11}
}

func (x *QueryEventsResponse) GetResponse() *v1.QueryResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_chaukas_spec_server_v1_server_proto protoreflect.FileDescriptor

const file_chaukas_spec_server_v1_server_proto_rawDesc = "" +
	"\n" +
	"#chaukas/spec/server/v1/server.proto\x12\x16chaukas.spec.server.v1\x1a#chaukas/spec/common/v1/events.proto\x1a\"chaukas/spec/common/v1/query.proto\"k\n" +
	"\x13IngestEventResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fprocessed_at\x18\x03 \x01(\x03R\vprocessedAt\"\xb1\x01\n" +
	"\x18IngestEventBatchResponse\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12%\n" +
	"\x0eaccepted_count\x18\x02 \x01(\x05R\racceptedCount\x12%\n" +
	"\x0erejected_count\x18\x03 \x01(\x05R\rrejectedCount\x12,\n" +
	"\x12rejected_event_ids\x18\x04 \x03(\tR\x10rejectedEventIds\"\x94\x01\n" +
	"\x14GetEventStatsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12@\n" +
	"\n" +
	"time_range\x18\x03 \x01(\v2!.chaukas.spec.common.v1.TimeRangeR\ttimeRange\"\xc0\x02\n" +
	"\x15GetEventStatsResponse\x12!\n" +
	"\ftotal_events\x18\x01 \x01(\x03R\vtotalEvents\x12%\n" +
	"\x0etotal_sessions\x18\x02 \x01(\x03R\rtotalSessions\x12e\n" +
	"\x0eevents_by_type\x18\x03 \x03(\v2?.chaukas.spec.server.v1.GetEventStatsResponse.EventsByTypeEntryR\feventsByType\x125\n" +
	"\x17avg_session_duration_ms\x18\x04 \x01(\x01R\x14avgSessionDurationMs\x1a?\n" +
	"\x11EventsByTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x10\n" +
	"\x0eHealthzRequest\"\x11\n" +
	"\x0fHealthzResponse\"\x18\n" +
	"\x16GetCapabilitiesRequest\"c\n" +
	"\x17GetCapabilitiesResponse\x12H\n" +
	"\fcapabilities\x18\x01 \x01(\v2$.chaukas.spec.common.v1.CapabilitiesR\fcapabilities\"I\n" +
	"\x12IngestEventRequest\x123\n" +
	"\x05event\x18\x01 \x01(\v2\x1d.chaukas.spec.common.v1.EventR\x05event\"^\n" +
	"\x17IngestEventBatchRequest\x12C\n" +
	"\vevent_batch\x18\x01 \x01(\v2\".chaukas.spec.common.v1.EventBatchR\n" +
	"eventBatch\"P\n" +
	"\x12QueryEventsRequest\x12:\n" +
	"\x05query\x18\x01 \x01(\v2$.chaukas.spec.common.v1.QueryRequestR\x05query\"X\n" +
	"\x13QueryEventsResponse\x12A\n" +
	"\bresponse\x18\x01 \x01(\v2%.chaukas.spec.common.v1.QueryResponseR\bresponse2\x9b\x05\n" +
	"\x14ChaukasServerService\x12Z\n" +
	"\aHealthz\x12&.chaukas.spec.server.v1.HealthzRequest\x1a'.chaukas.spec.server.v1.HealthzResponse\x12r\n" +
	"\x0fGetCapabilities\x12..chaukas.spec.server.v1.GetCapabilitiesRequest\x1a/.chaukas.spec.server.v1.GetCapabilitiesResponse\x12f\n" +
	"\vIngestEvent\x12*.chaukas.spec.server.v1.IngestEventRequest\x1a+.chaukas.spec.server.v1.IngestEventResponse\x12u\n" +
	"\x10IngestEventBatch\x12/.chaukas.spec.server.v1.IngestEventBatchRequest\x1a0.chaukas.spec.server.v1.IngestEventBatchResponse\x12f\n" +
	"\vQueryEvents\x12*.chaukas.spec.server.v1.QueryEventsRequest\x1a+.chaukas.spec.server.v1.QueryEventsResponse\x12l\n" +
	"\rGetEventStats\x12,.chaukas.spec.server.v1.GetEventStatsRequest\x1a-.chaukas.spec.server.v1.GetEventStatsResponseB=Z;github.com/chaukasai/chaukas-spec/chaukas/spec/server/v1;v1b\x06proto3"

var (
	file_chaukas_spec_server_v1_server_proto_rawDescOnce sync.Once
	file_chaukas_spec_server_v1_server_proto_rawDescData []byte
)

func file_chaukas_spec_server_v1_server_proto_rawDescGZIP() []byte {
	file_chaukas_spec_server_v1_server_proto_rawDescOnce.Do(func() {
		file_chaukas_spec_server_v1_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chaukas_spec_server_v1_server_proto_rawDesc), len(file_chaukas_spec_server_v1_server_proto_rawDesc)))
	})
	return file_chaukas_spec_server_v1_server_proto_rawDescData
}

var file_chaukas_spec_server_v1_server_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_chaukas_spec_server_v1_server_proto_goTypes = []any{
	(*IngestEventResponse)(nil),      // 0: chaukas.spec.server.v1.IngestEventResponse
	(*IngestEventBatchResponse)(nil), // 1: chaukas.spec.server.v1.IngestEventBatchResponse
	(*GetEventStatsRequest)(nil),     // 2: chaukas.spec.server.v1.GetEventStatsRequest
	(*GetEventStatsResponse)(nil),    // 3: chaukas.spec.server.v1.GetEventStatsResponse
	(*HealthzRequest)(nil),           // 4: chaukas.spec.server.v1.HealthzRequest
	(*HealthzResponse)(nil),          // 5: chaukas.spec.server.v1.HealthzResponse
	(*GetCapabilitiesRequest)(nil),   // 6: chaukas.spec.server.v1.GetCapabilitiesRequest
	(*GetCapabilitiesResponse)(nil),  // 7: chaukas.spec.server.v1.GetCapabilitiesResponse
	(*IngestEventRequest)(nil),       // 8: chaukas.spec.server.v1.IngestEventRequest
	(*IngestEventBatchRequest)(nil),  // 9: chaukas.spec.server.v1.IngestEventBatchRequest
	(*QueryEventsRequest)(nil),       // 10: chaukas.spec.server.v1.QueryEventsRequest
	(*QueryEventsResponse)(nil),      // 11: chaukas.spec.server.v1.QueryEventsResponse
	nil,                              // 12: chaukas.spec.server.v1.GetEventStatsResponse.EventsByTypeEntry
	(*v1.TimeRange)(nil),             // 13: chaukas.spec.common.v1.TimeRange
	(*v1.Capabilities)(nil),          // 14: chaukas.spec.common.v1.Capabilities
	(*v1.Event)(nil),                 // 15: chaukas.spec.common.v1.Event
	(*v1.EventBatch)(nil),            // 16: chaukas.spec.common.v1.EventBatch
	(*v1.QueryRequest)(nil),          // 17: chaukas.spec.common.v1.QueryRequest
	(*v1.QueryResponse)(nil),         // 18: chaukas.spec.common.v1.QueryResponse
}
var file_chaukas_spec_server_v1_server_proto_depIdxs = []int32{
	13, // 0: chaukas.spec.server.v1.GetEventStatsRequest.time_range:type_name -> chaukas.spec.common.v1.TimeRange
	12, // 1: chaukas.spec.server.v1.GetEventStatsResponse.events_by_type:type_name -> chaukas.spec.server.v1.GetEventStatsResponse.EventsByTypeEntry
	14, // 2: chaukas.spec.server.v1.GetCapabilitiesResponse.capabilities:type_name -> chaukas.spec.common.v1.Capabilities
	15, // 3: chaukas.spec.server.v1.IngestEventRequest.event:type_name -> chaukas.spec.common.v1.Event
	16, // 4: chaukas.spec.server.v1.IngestEventBatchRequest.event_batch:type_name -> chaukas.spec.common.v1.EventBatch
	17, // 5: chaukas.spec.server.v1.QueryEventsRequest.query:type_name -> chaukas.spec.common.v1.QueryRequest
	18, // 6: chaukas.spec.server.v1.QueryEventsResponse.response:type_name -> chaukas.spec.common.v1.QueryResponse
	4,  // 7: chaukas.spec.server.v1.ChaukasServerService.Healthz:input_type -> chaukas.spec.server.v1.HealthzRequest
	6,  // 8: chaukas.spec.server.v1.ChaukasServerService.GetCapabilities:input_type -> chaukas.spec.server.v1.GetCapabilitiesRequest
	8,  // 9: chaukas.spec.server.v1.ChaukasServerService.IngestEvent:input_type -> chaukas.spec.server.v1.IngestEventRequest
	9,  // 10: chaukas.spec.server.v1.ChaukasServerService.IngestEventBatch:input_type -> chaukas.spec.server.v1.IngestEventBatchRequest
	10, // 11: chaukas.spec.server.v1.ChaukasServerService.QueryEvents:input_type -> chaukas.spec.server.v1.QueryEventsRequest
	2,  // 12: chaukas.spec.server.v1.ChaukasServerService.GetEventStats:input_type -> chaukas.spec.server.v1.GetEventStatsRequest
	5,  // 13: chaukas.spec.server.v1.ChaukasServerService.Healthz:output_type -> chaukas.spec.server.v1.HealthzResponse
	7,  // 14: chaukas.spec.server.v1.ChaukasServerService.GetCapabilities:output_type -> chaukas.spec.server.v1.GetCapabilitiesResponse
	0,  // 15: chaukas.spec.server.v1.ChaukasServerService.IngestEvent:output_type -> chaukas.spec.server.v1.IngestEventResponse
	1,  // 16: chaukas.spec.server.v1.ChaukasServerService.IngestEventBatch:output_type -> chaukas.spec.server.v1.IngestEventBatchResponse
	11, // 17: chaukas.spec.server.v1.ChaukasServerService.QueryEvents:output_type -> chaukas.spec.server.v1.QueryEventsResponse
	3,  // 18: chaukas.spec.server.v1.ChaukasServerService.GetEventStats:output_type -> chaukas.spec.server.v1.GetEventStatsResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_chaukas_spec_server_v1_server_proto_init() }
func file_chaukas_spec_server_v1_server_proto_init() {
	if File_chaukas_spec_server_v1_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chaukas_spec_server_v1_server_proto_rawDesc), len(file_chaukas_spec_server_v1_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chaukas_spec_server_v1_server_proto_goTypes,
		DependencyIndexes: file_chaukas_spec_server_v1_server_proto_depIdxs,
		MessageInfos:      file_chaukas_spec_server_v1_server_proto_msgTypes,
	}.Build()
	File_chaukas_spec_server_v1_server_proto = out.File
	file_chaukas_spec_server_v1_server_proto_goTypes = nil
	file_chaukas_spec_server_v1_server_proto_depIdxs = nil
}
