// Copyright 2025 Chaukas AI
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: chaukas/spec/client/v1/client.proto

package v1

import (
	v1 "github.com/chaukasai/chaukas-spec/chaukas/spec/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Health check request
type HealthzRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthzRequest) Reset() {
	*x = HealthzRequest{}
	mi := &file_chaukas_spec_client_v1_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthzRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzRequest) ProtoMessage() {}

func (x *HealthzRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chaukas_spec_client_v1_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzRequest.ProtoReflect.Descriptor instead.
func (*HealthzRequest) Descriptor() ([]byte, []int) {
	return file_chaukas_spec_client_v1_client_proto_rawDescGZIP(), []int{0}
}

// Health check response
type HealthzResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthzResponse) Reset() {
	*x = HealthzResponse{}
	mi := &file_chaukas_spec_client_v1_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthzResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzResponse) ProtoMessage() {}

func (x *HealthzResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chaukas_spec_client_v1_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzResponse.ProtoReflect.Descriptor instead.
func (*HealthzResponse) Descriptor() ([]byte, []int) {
	return file_chaukas_spec_client_v1_client_proto_rawDescGZIP(), []int{1}
}

// Get capabilities request
type GetCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapabilitiesRequest) Reset() {
	*x = GetCapabilitiesRequest{}
	mi := &file_chaukas_spec_client_v1_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesRequest) ProtoMessage() {}

func (x *GetCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chaukas_spec_client_v1_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_chaukas_spec_client_v1_client_proto_rawDescGZIP(), []int{2}
}

// Get capabilities response
type GetCapabilitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capabilities  *v1.Capabilities       `protobuf:"bytes,1,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapabilitiesResponse) Reset() {
	*x = GetCapabilitiesResponse{}
	mi := &file_chaukas_spec_client_v1_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesResponse) ProtoMessage() {}

func (x *GetCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chaukas_spec_client_v1_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_chaukas_spec_client_v1_client_proto_rawDescGZIP(), []int{3}
}

func (x *GetCapabilitiesResponse) GetCapabilities() *v1.Capabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// Ingest single event request
type IngestEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *v1.Event              `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestEventRequest) Reset() {
	*x = IngestEventRequest{}
	mi := &file_chaukas_spec_client_v1_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEventRequest) ProtoMessage() {}

func (x *IngestEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chaukas_spec_client_v1_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEventRequest.ProtoReflect.Descriptor instead.
func (*IngestEventRequest) Descriptor() ([]byte, []int) {
	return file_chaukas_spec_client_v1_client_proto_rawDescGZIP(), []int{4}
}

func (x *IngestEventRequest) GetEvent() *v1.Event {
	if x != nil {
		return x.Event
	}
	return nil
}

// Ingest single event response
type IngestEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestEventResponse) Reset() {
	*x = IngestEventResponse{}
	mi := &file_chaukas_spec_client_v1_client_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEventResponse) ProtoMessage() {}

func (x *IngestEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chaukas_spec_client_v1_client_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEventResponse.ProtoReflect.Descriptor instead.
func (*IngestEventResponse) Descriptor() ([]byte, []int) {
	return file_chaukas_spec_client_v1_client_proto_rawDescGZIP(), []int{5}
}

// Ingest event batch request
type IngestEventBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventBatch    *v1.EventBatch         `protobuf:"bytes,1,opt,name=event_batch,json=eventBatch,proto3" json:"event_batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestEventBatchRequest) Reset() {
	*x = IngestEventBatchRequest{}
	mi := &file_chaukas_spec_client_v1_client_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEventBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEventBatchRequest) ProtoMessage() {}

func (x *IngestEventBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chaukas_spec_client_v1_client_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEventBatchRequest.ProtoReflect.Descriptor instead.
func (*IngestEventBatchRequest) Descriptor() ([]byte, []int) {
	return file_chaukas_spec_client_v1_client_proto_rawDescGZIP(), []int{6}
}

func (x *IngestEventBatchRequest) GetEventBatch() *v1.EventBatch {
	if x != nil {
		return x.EventBatch
	}
	return nil
}

// Ingest event batch response
type IngestEventBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestEventBatchResponse) Reset() {
	*x = IngestEventBatchResponse{}
	mi := &file_chaukas_spec_client_v1_client_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestEventBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestEventBatchResponse) ProtoMessage() {}

func (x *IngestEventBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chaukas_spec_client_v1_client_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestEventBatchResponse.ProtoReflect.Descriptor instead.
func (*IngestEventBatchResponse) Descriptor() ([]byte, []int) {
	return file_chaukas_spec_client_v1_client_proto_rawDescGZIP(), []int{7}
}

// Query events request
type QueryEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *v1.QueryRequest       `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEventsRequest) Reset() {
	*x = QueryEventsRequest{}
	mi := &file_chaukas_spec_client_v1_client_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEventsRequest) ProtoMessage() {}

func (x *QueryEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chaukas_spec_client_v1_client_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEventsRequest.ProtoReflect.Descriptor instead.
func (*QueryEventsRequest) Descriptor() ([]byte, []int) {
	return file_chaukas_spec_client_v1_client_proto_rawDescGZIP(), []int{8}
}

func (x *QueryEventsRequest) GetQuery() *v1.QueryRequest {
	if x != nil {
		return x.Query
	}
	return nil
}

// Query events response
type QueryEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *v1.QueryResponse      `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEventsResponse) Reset() {
	*x = QueryEventsResponse{}
	mi := &file_chaukas_spec_client_v1_client_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEventsResponse) ProtoMessage() {}

func (x *QueryEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chaukas_spec_client_v1_client_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEventsResponse.ProtoReflect.Descriptor instead.
func (*QueryEventsResponse) Descriptor() ([]byte, []int) {
	return file_chaukas_spec_client_v1_client_proto_rawDescGZIP(), []int{9}
}

func (x *QueryEventsResponse) GetResponse() *v1.QueryResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_chaukas_spec_client_v1_client_proto protoreflect.FileDescriptor

const file_chaukas_spec_client_v1_client_proto_rawDesc = "" +
	"\n" +
	"#chaukas/spec/client/v1/client.proto\x12\x16chaukas.spec.client.v1\x1a#chaukas/spec/common/v1/events.proto\x1a\"chaukas/spec/common/v1/query.proto\"\x10\n" +
	"\x0eHealthzRequest\"\x11\n" +
	"\x0fHealthzResponse\"\x18\n" +
	"\x16GetCapabilitiesRequest\"c\n" +
	"\x17GetCapabilitiesResponse\x12H\n" +
	"\fcapabilities\x18\x01 \x01(\v2$.chaukas.spec.common.v1.CapabilitiesR\fcapabilities\"I\n" +
	"\x12IngestEventRequest\x123\n" +
	"\x05event\x18\x01 \x01(\v2\x1d.chaukas.spec.common.v1.EventR\x05event\"\x15\n" +
	"\x13IngestEventResponse\"^\n" +
	"\x17IngestEventBatchRequest\x12C\n" +
	"\vevent_batch\x18\x01 \x01(\v2\".chaukas.spec.common.v1.EventBatchR\n" +
	"eventBatch\"\x1a\n" +
	"\x18IngestEventBatchResponse\"P\n" +
	"\x12QueryEventsRequest\x12:\n" +
	"\x05query\x18\x01 \x01(\v2$.chaukas.spec.common.v1.QueryRequestR\x05query\"X\n" +
	"\x13QueryEventsResponse\x12A\n" +
	"\bresponse\x18\x01 \x01(\v2%.chaukas.spec.common.v1.QueryResponseR\bresponse2\xad\x04\n" +
	"\x14ChaukasClientService\x12Z\n" +
	"\aHealthz\x12&.chaukas.spec.client.v1.HealthzRequest\x1a'.chaukas.spec.client.v1.HealthzResponse\x12r\n" +
	"\x0fGetCapabilities\x12..chaukas.spec.client.v1.GetCapabilitiesRequest\x1a/.chaukas.spec.client.v1.GetCapabilitiesResponse\x12f\n" +
	"\vIngestEvent\x12*.chaukas.spec.client.v1.IngestEventRequest\x1a+.chaukas.spec.client.v1.IngestEventResponse\x12u\n" +
	"\x10IngestEventBatch\x12/.chaukas.spec.client.v1.IngestEventBatchRequest\x1a0.chaukas.spec.client.v1.IngestEventBatchResponse\x12f\n" +
	"\vQueryEvents\x12*.chaukas.spec.client.v1.QueryEventsRequest\x1a+.chaukas.spec.client.v1.QueryEventsResponseB=Z;github.com/chaukasai/chaukas-spec/chaukas/spec/client/v1;v1b\x06proto3"

var (
	file_chaukas_spec_client_v1_client_proto_rawDescOnce sync.Once
	file_chaukas_spec_client_v1_client_proto_rawDescData []byte
)

func file_chaukas_spec_client_v1_client_proto_rawDescGZIP() []byte {
	file_chaukas_spec_client_v1_client_proto_rawDescOnce.Do(func() {
		file_chaukas_spec_client_v1_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chaukas_spec_client_v1_client_proto_rawDesc), len(file_chaukas_spec_client_v1_client_proto_rawDesc)))
	})
	return file_chaukas_spec_client_v1_client_proto_rawDescData
}

var file_chaukas_spec_client_v1_client_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_chaukas_spec_client_v1_client_proto_goTypes = []any{
	(*HealthzRequest)(nil),           // 0: chaukas.spec.client.v1.HealthzRequest
	(*HealthzResponse)(nil),          // 1: chaukas.spec.client.v1.HealthzResponse
	(*GetCapabilitiesRequest)(nil),   // 2: chaukas.spec.client.v1.GetCapabilitiesRequest
	(*GetCapabilitiesResponse)(nil),  // 3: chaukas.spec.client.v1.GetCapabilitiesResponse
	(*IngestEventRequest)(nil),       // 4: chaukas.spec.client.v1.IngestEventRequest
	(*IngestEventResponse)(nil),      // 5: chaukas.spec.client.v1.IngestEventResponse
	(*IngestEventBatchRequest)(nil),  // 6: chaukas.spec.client.v1.IngestEventBatchRequest
	(*IngestEventBatchResponse)(nil), // 7: chaukas.spec.client.v1.IngestEventBatchResponse
	(*QueryEventsRequest)(nil),       // 8: chaukas.spec.client.v1.QueryEventsRequest
	(*QueryEventsResponse)(nil),      // 9: chaukas.spec.client.v1.QueryEventsResponse
	(*v1.Capabilities)(nil),          // 10: chaukas.spec.common.v1.Capabilities
	(*v1.Event)(nil),                 // 11: chaukas.spec.common.v1.Event
	(*v1.EventBatch)(nil),            // 12: chaukas.spec.common.v1.EventBatch
	(*v1.QueryRequest)(nil),          // 13: chaukas.spec.common.v1.QueryRequest
	(*v1.QueryResponse)(nil),         // 14: chaukas.spec.common.v1.QueryResponse
}
var file_chaukas_spec_client_v1_client_proto_depIdxs = []int32{
	10, // 0: chaukas.spec.client.v1.GetCapabilitiesResponse.capabilities:type_name -> chaukas.spec.common.v1.Capabilities
	11, // 1: chaukas.spec.client.v1.IngestEventRequest.event:type_name -> chaukas.spec.common.v1.Event
	12, // 2: chaukas.spec.client.v1.IngestEventBatchRequest.event_batch:type_name -> chaukas.spec.common.v1.EventBatch
	13, // 3: chaukas.spec.client.v1.QueryEventsRequest.query:type_name -> chaukas.spec.common.v1.QueryRequest
	14, // 4: chaukas.spec.client.v1.QueryEventsResponse.response:type_name -> chaukas.spec.common.v1.QueryResponse
	0,  // 5: chaukas.spec.client.v1.ChaukasClientService.Healthz:input_type -> chaukas.spec.client.v1.HealthzRequest
	2,  // 6: chaukas.spec.client.v1.ChaukasClientService.GetCapabilities:input_type -> chaukas.spec.client.v1.GetCapabilitiesRequest
	4,  // 7: chaukas.spec.client.v1.ChaukasClientService.IngestEvent:input_type -> chaukas.spec.client.v1.IngestEventRequest
	6,  // 8: chaukas.spec.client.v1.ChaukasClientService.IngestEventBatch:input_type -> chaukas.spec.client.v1.IngestEventBatchRequest
	8,  // 9: chaukas.spec.client.v1.ChaukasClientService.QueryEvents:input_type -> chaukas.spec.client.v1.QueryEventsRequest
	1,  // 10: chaukas.spec.client.v1.ChaukasClientService.Healthz:output_type -> chaukas.spec.client.v1.HealthzResponse
	3,  // 11: chaukas.spec.client.v1.ChaukasClientService.GetCapabilities:output_type -> chaukas.spec.client.v1.GetCapabilitiesResponse
	5,  // 12: chaukas.spec.client.v1.ChaukasClientService.IngestEvent:output_type -> chaukas.spec.client.v1.IngestEventResponse
	7,  // 13: chaukas.spec.client.v1.ChaukasClientService.IngestEventBatch:output_type -> chaukas.spec.client.v1.IngestEventBatchResponse
	9,  // 14: chaukas.spec.client.v1.ChaukasClientService.QueryEvents:output_type -> chaukas.spec.client.v1.QueryEventsResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_chaukas_spec_client_v1_client_proto_init() }
func file_chaukas_spec_client_v1_client_proto_init() {
	if File_chaukas_spec_client_v1_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chaukas_spec_client_v1_client_proto_rawDesc), len(file_chaukas_spec_client_v1_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chaukas_spec_client_v1_client_proto_goTypes,
		DependencyIndexes: file_chaukas_spec_client_v1_client_proto_depIdxs,
		MessageInfos:      file_chaukas_spec_client_v1_client_proto_msgTypes,
	}.Build()
	File_chaukas_spec_client_v1_client_proto = out.File
	file_chaukas_spec_client_v1_client_proto_goTypes = nil
	file_chaukas_spec_client_v1_client_proto_depIdxs = nil
}
