// Copyright 2025 Chaukas AI
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: chaukas/spec/common/v1/query.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SortOrder int32

const (
	SortOrder_SORT_ORDER_UNSPECIFIED SortOrder = 0
	SortOrder_SORT_ORDER_ASC         SortOrder = 1
	SortOrder_SORT_ORDER_DESC        SortOrder = 2
)

// Enum value maps for SortOrder.
var (
	SortOrder_name = map[int32]string{
		0: "SORT_ORDER_UNSPECIFIED",
		1: "SORT_ORDER_ASC",
		2: "SORT_ORDER_DESC",
	}
	SortOrder_value = map[string]int32{
		"SORT_ORDER_UNSPECIFIED": 0,
		"SORT_ORDER_ASC":         1,
		"SORT_ORDER_DESC":        2,
	}
)

func (x SortOrder) Enum() *SortOrder {
	p := new(SortOrder)
	*p = x
	return p
}

func (x SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_chaukas_spec_common_v1_query_proto_enumTypes[0].Descriptor()
}

func (SortOrder) Type() protoreflect.EnumType {
	return &file_chaukas_spec_common_v1_query_proto_enumTypes[0]
}

func (x SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortOrder.Descriptor instead.
func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return file_chaukas_spec_common_v1_query_proto_rawDescGZIP(), []int{0}
}

type TimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_chaukas_spec_common_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_chaukas_spec_common_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_chaukas_spec_common_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *TimeRange) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *TimeRange) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type QueryFilter struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	TenantId  string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ProjectId string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Optional scoping
	SessionId string `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AgentId   string `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SpanId    string `protobuf:"bytes,5,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	TraceId   string `protobuf:"bytes,6,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"` // Filter by distributed trace identifier
	// Event fields
	Types      []EventType   `protobuf:"varint,10,rep,packed,name=types,proto3,enum=chaukas.spec.common.v1.EventType" json:"types,omitempty"`
	Statuses   []EventStatus `protobuf:"varint,11,rep,packed,name=statuses,proto3,enum=chaukas.spec.common.v1.EventStatus" json:"statuses,omitempty"`
	Severities []Severity    `protobuf:"varint,12,rep,packed,name=severities,proto3,enum=chaukas.spec.common.v1.Severity" json:"severities,omitempty"`
	// Tags & text
	Tags      []string `protobuf:"bytes,20,rep,name=tags,proto3" json:"tags,omitempty"`
	TextQuery string   `protobuf:"bytes,21,opt,name=text_query,json=textQuery,proto3" json:"text_query,omitempty"` // full-text (implementation-defined)
	// Time
	Time          *TimeRange `protobuf:"bytes,30,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryFilter) Reset() {
	*x = QueryFilter{}
	mi := &file_chaukas_spec_common_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryFilter) ProtoMessage() {}

func (x *QueryFilter) ProtoReflect() protoreflect.Message {
	mi := &file_chaukas_spec_common_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryFilter.ProtoReflect.Descriptor instead.
func (*QueryFilter) Descriptor() ([]byte, []int) {
	return file_chaukas_spec_common_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryFilter) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *QueryFilter) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *QueryFilter) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *QueryFilter) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *QueryFilter) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *QueryFilter) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *QueryFilter) GetTypes() []EventType {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *QueryFilter) GetStatuses() []EventStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *QueryFilter) GetSeverities() []Severity {
	if x != nil {
		return x.Severities
	}
	return nil
}

func (x *QueryFilter) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *QueryFilter) GetTextQuery() string {
	if x != nil {
		return x.TextQuery
	}
	return ""
}

func (x *QueryFilter) GetTime() *TimeRange {
	if x != nil {
		return x.Time
	}
	return nil
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *QueryFilter           `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // default 100, max e.g. 1000
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	OrderByTime   SortOrder              `protobuf:"varint,4,opt,name=order_by_time,json=orderByTime,proto3,enum=chaukas.spec.common.v1.SortOrder" json:"order_by_time,omitempty"` // default DESC
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_chaukas_spec_common_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chaukas_spec_common_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_chaukas_spec_common_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryRequest) GetFilter() *QueryFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *QueryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *QueryRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *QueryRequest) GetOrderByTime() SortOrder {
	if x != nil {
		return x.OrderByTime
	}
	return SortOrder_SORT_ORDER_UNSPECIFIED
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_chaukas_spec_common_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chaukas_spec_common_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_chaukas_spec_common_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *QueryResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type Capabilities struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WormRetention    bool                   `protobuf:"varint,1,opt,name=worm_retention,json=wormRetention,proto3" json:"worm_retention,omitempty"`
	AuditProofs      bool                   `protobuf:"varint,2,opt,name=audit_proofs,json=auditProofs,proto3" json:"audit_proofs,omitempty"`
	DistributedQuery bool                   `protobuf:"varint,3,opt,name=distributed_query,json=distributedQuery,proto3" json:"distributed_query,omitempty"`
	Rbac             bool                   `protobuf:"varint,4,opt,name=rbac,proto3" json:"rbac,omitempty"`
	Sso              bool                   `protobuf:"varint,5,opt,name=sso,proto3" json:"sso,omitempty"`
	PolicyDecisions  bool                   `protobuf:"varint,6,opt,name=policy_decisions,json=policyDecisions,proto3" json:"policy_decisions,omitempty"`
	DataAccessEvents bool                   `protobuf:"varint,7,opt,name=data_access_events,json=dataAccessEvents,proto3" json:"data_access_events,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_chaukas_spec_common_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_chaukas_spec_common_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_chaukas_spec_common_v1_query_proto_rawDescGZIP(), []int{4}
}

func (x *Capabilities) GetWormRetention() bool {
	if x != nil {
		return x.WormRetention
	}
	return false
}

func (x *Capabilities) GetAuditProofs() bool {
	if x != nil {
		return x.AuditProofs
	}
	return false
}

func (x *Capabilities) GetDistributedQuery() bool {
	if x != nil {
		return x.DistributedQuery
	}
	return false
}

func (x *Capabilities) GetRbac() bool {
	if x != nil {
		return x.Rbac
	}
	return false
}

func (x *Capabilities) GetSso() bool {
	if x != nil {
		return x.Sso
	}
	return false
}

func (x *Capabilities) GetPolicyDecisions() bool {
	if x != nil {
		return x.PolicyDecisions
	}
	return false
}

func (x *Capabilities) GetDataAccessEvents() bool {
	if x != nil {
		return x.DataAccessEvents
	}
	return false
}

var File_chaukas_spec_common_v1_query_proto protoreflect.FileDescriptor

const file_chaukas_spec_common_v1_query_proto_rawDesc = "" +
	"\n" +
	"\"chaukas/spec/common/v1/query.proto\x12\x16chaukas.spec.common.v1\x1a#chaukas/spec/common/v1/events.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"k\n" +
	"\tTimeRange\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\"\xdd\x03\n" +
	"\vQueryFilter\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x12\x17\n" +
	"\aspan_id\x18\x05 \x01(\tR\x06spanId\x12\x19\n" +
	"\btrace_id\x18\x06 \x01(\tR\atraceId\x127\n" +
	"\x05types\x18\n" +
	" \x03(\x0e2!.chaukas.spec.common.v1.EventTypeR\x05types\x12?\n" +
	"\bstatuses\x18\v \x03(\x0e2#.chaukas.spec.common.v1.EventStatusR\bstatuses\x12@\n" +
	"\n" +
	"severities\x18\f \x03(\x0e2 .chaukas.spec.common.v1.SeverityR\n" +
	"severities\x12\x12\n" +
	"\x04tags\x18\x14 \x03(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"text_query\x18\x15 \x01(\tR\ttextQuery\x125\n" +
	"\x04time\x18\x1e \x01(\v2!.chaukas.spec.common.v1.TimeRangeR\x04time\"\xce\x01\n" +
	"\fQueryRequest\x12;\n" +
	"\x06filter\x18\x01 \x01(\v2#.chaukas.spec.common.v1.QueryFilterR\x06filter\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12E\n" +
	"\rorder_by_time\x18\x04 \x01(\x0e2!.chaukas.spec.common.v1.SortOrderR\vorderByTime\"n\n" +
	"\rQueryResponse\x125\n" +
	"\x06events\x18\x01 \x03(\v2\x1d.chaukas.spec.common.v1.EventR\x06events\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x84\x02\n" +
	"\fCapabilities\x12%\n" +
	"\x0eworm_retention\x18\x01 \x01(\bR\rwormRetention\x12!\n" +
	"\faudit_proofs\x18\x02 \x01(\bR\vauditProofs\x12+\n" +
	"\x11distributed_query\x18\x03 \x01(\bR\x10distributedQuery\x12\x12\n" +
	"\x04rbac\x18\x04 \x01(\bR\x04rbac\x12\x10\n" +
	"\x03sso\x18\x05 \x01(\bR\x03sso\x12)\n" +
	"\x10policy_decisions\x18\x06 \x01(\bR\x0fpolicyDecisions\x12,\n" +
	"\x12data_access_events\x18\a \x01(\bR\x10dataAccessEvents*P\n" +
	"\tSortOrder\x12\x1a\n" +
	"\x16SORT_ORDER_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSORT_ORDER_ASC\x10\x01\x12\x13\n" +
	"\x0fSORT_ORDER_DESC\x10\x02B=Z;github.com/chaukasai/chaukas-spec/chaukas/spec/common/v1;v1b\x06proto3"

var (
	file_chaukas_spec_common_v1_query_proto_rawDescOnce sync.Once
	file_chaukas_spec_common_v1_query_proto_rawDescData []byte
)

func file_chaukas_spec_common_v1_query_proto_rawDescGZIP() []byte {
	file_chaukas_spec_common_v1_query_proto_rawDescOnce.Do(func() {
		file_chaukas_spec_common_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chaukas_spec_common_v1_query_proto_rawDesc), len(file_chaukas_spec_common_v1_query_proto_rawDesc)))
	})
	return file_chaukas_spec_common_v1_query_proto_rawDescData
}

var file_chaukas_spec_common_v1_query_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chaukas_spec_common_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_chaukas_spec_common_v1_query_proto_goTypes = []any{
	(SortOrder)(0),                // 0: chaukas.spec.common.v1.SortOrder
	(*TimeRange)(nil),             // 1: chaukas.spec.common.v1.TimeRange
	(*QueryFilter)(nil),           // 2: chaukas.spec.common.v1.QueryFilter
	(*QueryRequest)(nil),          // 3: chaukas.spec.common.v1.QueryRequest
	(*QueryResponse)(nil),         // 4: chaukas.spec.common.v1.QueryResponse
	(*Capabilities)(nil),          // 5: chaukas.spec.common.v1.Capabilities
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(EventType)(0),                // 7: chaukas.spec.common.v1.EventType
	(EventStatus)(0),              // 8: chaukas.spec.common.v1.EventStatus
	(Severity)(0),                 // 9: chaukas.spec.common.v1.Severity
	(*Event)(nil),                 // 10: chaukas.spec.common.v1.Event
}
var file_chaukas_spec_common_v1_query_proto_depIdxs = []int32{
	6,  // 0: chaukas.spec.common.v1.TimeRange.start:type_name -> google.protobuf.Timestamp
	6,  // 1: chaukas.spec.common.v1.TimeRange.end:type_name -> google.protobuf.Timestamp
	7,  // 2: chaukas.spec.common.v1.QueryFilter.types:type_name -> chaukas.spec.common.v1.EventType
	8,  // 3: chaukas.spec.common.v1.QueryFilter.statuses:type_name -> chaukas.spec.common.v1.EventStatus
	9,  // 4: chaukas.spec.common.v1.QueryFilter.severities:type_name -> chaukas.spec.common.v1.Severity
	1,  // 5: chaukas.spec.common.v1.QueryFilter.time:type_name -> chaukas.spec.common.v1.TimeRange
	2,  // 6: chaukas.spec.common.v1.QueryRequest.filter:type_name -> chaukas.spec.common.v1.QueryFilter
	0,  // 7: chaukas.spec.common.v1.QueryRequest.order_by_time:type_name -> chaukas.spec.common.v1.SortOrder
	10, // 8: chaukas.spec.common.v1.QueryResponse.events:type_name -> chaukas.spec.common.v1.Event
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_chaukas_spec_common_v1_query_proto_init() }
func file_chaukas_spec_common_v1_query_proto_init() {
	if File_chaukas_spec_common_v1_query_proto != nil {
		return
	}
	file_chaukas_spec_common_v1_events_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chaukas_spec_common_v1_query_proto_rawDesc), len(file_chaukas_spec_common_v1_query_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chaukas_spec_common_v1_query_proto_goTypes,
		DependencyIndexes: file_chaukas_spec_common_v1_query_proto_depIdxs,
		EnumInfos:         file_chaukas_spec_common_v1_query_proto_enumTypes,
		MessageInfos:      file_chaukas_spec_common_v1_query_proto_msgTypes,
	}.Build()
	File_chaukas_spec_common_v1_query_proto = out.File
	file_chaukas_spec_common_v1_query_proto_goTypes = nil
	file_chaukas_spec_common_v1_query_proto_depIdxs = nil
}
